cat("# This file auto-generated by tools/get-R-poly-test-vectors.R\n")
cat(sprintf("# Using: %s\n", R.Version()$version.string))
cat("import numpy as np\n")

options(digits=20)
library(splines)
x <- (1.5)^(0:19)

MISSING <- "MISSING"

is.missing <- function(obj) {
  length(obj) == 1 && obj == MISSING
}

pyprint <- function(arr) {
  if (is.missing(arr)) {
    cat("None\n")
  } else {
    cat("np.array([")
    for (val in arr) {
      cat(val)
      cat(", ")
    }
    cat("])")
    if (!is.null(dim(arr))) {
      cat(".reshape((")
      for (size in dim(arr)) {
        cat(sprintf("%s, ", size))
      }
      cat("), order=\"F\")")
    }
    cat("\n")
  }
}

num.tests <- 0
dump.poly <- function(degree, raw) {
  cat("--BEGIN TEST CASE--\n")
  cat(sprintf("degree=%s\n", degree))
  cat(sprintf("raw=%s\n", raw))
  
  args <- list(x=x, degree=degree, raw=raw)

  result <- do.call(poly, args)
  
  cat("output=")
  pyprint(result)
  cat("--END TEST CASE--\n")
  assign("num.tests", num.tests + 1, envir=.GlobalEnv)
}

cat("R_poly_test_x = ")
pyprint(x)
cat("R_poly_test_data = \"\"\"\n")

for (degree in c(1, 3, 5)) {
  for (raw in c(TRUE, FALSE)) {
    dump.poly(degree, raw)
  }
}
cat("\"\"\"\n")
cat(sprintf("R_poly_num_tests = %s\n", num.tests))
