# R code to dump the output from 'bs()' in many situations, for
# checking compatibility.
#
# Usage:
#   Rscript tools/get-R-bs-test-vectors.R > patsy/test_splines_bs_data.py
cat("# This file auto-generated by tools/get-R-bs-test-vectors.R\n")
cat(sprintf("# Using: %s\n", R.Version()$version.string))

options(digits=20)
library(splines)
x <- (1.5)^(0:19)

# Prints a flattened array (in Fortran order, as per R default)
pyprint <- function(arr) {
  cat("[")
  for (val in arr) {
    cat(val)
    cat(", ")
  }
  cat("]\n")
}

num.tests <- 0
dump.bs <- function(degree, df, knots,
                    intercept, Boundary.knots) {
  cat("--BEGIN TEST CASE--\n")
  cat(sprintf("degree=%s\n", degree))
  cat(sprintf("df=%s\n", if (is.null(df)) "None" else df))
  cat(sprintf("intercept=%s\n", intercept))
  cat("Boundary.knots=")
  if (is.null(Boundary.knots)) {
    cat("None\n")
  } else {
    pyprint(Boundary.knots)
  }
  cat("knots=")
  if (is.null(knots)) {
    cat("None\n")
  } else {
    pyprint(knots)
  }
  if (is.null(Boundary.knots)) {
    result <- bs(x, df=df, knots=knots,
                 intercept=intercept)
  } else {
    result <- bs(x, df=df, knots=knots,
                 intercept=intercept,
                 Boundary.knots=Boundary.knots)
  }

  cat("output_dim=")
  pyprint(dim(result))
  cat("output_values=")
  pyprint(result)
  cat("--END TEST CASE--\n")
  assign("num.tests", num.tests + 1, envir=.GlobalEnv)
}

cat("R_bs_test_x = ")
pyprint(x)
cat("R_bs_test_data = \"\"\"\n")

for (degree in c(1, 3, 5)) {
  for (intercept in c(TRUE, FALSE)) {
    for (Boundary.knots in list(NULL, c(0, 3000))) {
      for (df in c(3, 5, 12)) {
        if (df < degree + 2) {
          next
        } else {
          dump.bs(degree, df, NULL, intercept, Boundary.knots)
        }
      }
      for (knots in list(NULL, 100, 1000, c(10, 100, 1000))) {
        dump.bs(degree, NULL, knots, intercept, Boundary.knots)
      }
    }
  }
}
cat("\"\"\"\n")
cat(sprintf("R_bs_num_tests = %s\n", num.tests))
